<?php require('views/navbar.phtml');?>
<!-- Page Content -->


    <!--After fetching all adverts, loops through the object and returns advert details as well as user details for that advert-->
            <?php
                foreach($view->adverts as $advert)
                echo "<div class=\"container\">
            <div class=\"row\">
            <div class=\"col-lg-3\">
            <h1 class=\"my-4\">Listing Number: $advert->AdvertID</h1>
            <div class=\"list-group\">
            <form method=\"post\">
                        <button type=\"submit\" id=\"saveAdvert\" name=\"saveAdvert\" class=\"btn btn-block btn-primary\">Save Advert</button>
                        <button type=\"submit\" id=\"unsaveAdvert\" name=\"unsaveAdvert\" class=\"btn btn-block btn-primary\">Unsave Advert</button>
                    </form>
            </div>
            </div>
            <!-- /.col-lg-3 -->
            <div class=\"col-lg-9\">
            <div class=\"card mt-4\">
            <img class=\"card-img-top img-fluid\" src=\"img/$advert->PhotoName\" alt=\"\">
            <div class=\"card-body\">
            <h3 class=\"card-title\">$advert->AdvertName</h3>
            <h4>£ $advert->AdvertPrice</h4>
            <p class=\"card-text\">$advert->AdvertDescription</p>
            </div>
            </div>
            <!-- /.card -->
            <div class=\"card card-outline-secondary my-4\">
            <div class=\"card-header\">
            Seller Details
            </div>
            
            <div class=\"card-body\">"?>
                    <?php if(isset($_SESSION['Username']))
                        {
                            echo "<strong><p>Username:   </strong>$advert->Username
                    <hr>
                    <strong><p>Email:   </strong>$advert->Email
                    <hr>
                    <strong><p>Postcode:   </strong>$advert->Address
                    <hr>
                    <strong><p>Phone Number:   </strong>$advert->Phone
                    ";
                        }
                        else echo "Seller details are available upon registration";
                        ?>



            </div>
            </div>
            <!-- /.card -->
            </div>
            <!-- /.col-lg-9 -->
            </div>
            </div>
            <!-- /.container -->";





<!-- Bootstrap core JavaScript -->
<script src="../vendor/jquery/jquery.min.js"></script>
<script src="../vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>

<?php require_once("footer.phtml")?>