<?php require('views/navbar.phtml');?>
<?php require('views/dashnav.phtml');?>
<div class="col-lg-9">

    <div class="card mt-4">
        <form method="post" enctype="multipart/form-data">
        <img class="card-img-top img-fluid" src="http://placehold.it/900x400" alt="">
        <div class="card-body">
            <div class="form-group">
                <input type="file" name="file" id="file" placeholder="Upload an image">
            </div>
            <div class="form-group">
                <input type="text" class="form-control" name="name" placeholder="Product Name"/>
            </div>
            <div class="form-group">
                <input type="text" class="form-control" name="price" placeholder="Product Price"/>
            </div>
            <div class="form-group">
                <input type="text" class="form-control" name="description" placeholder="Product Description"/>
            </div>
            <p>Product Type:</p>
            <div class="form-group">
                <input type ="radio" id="singles" name="type" value="Singles"><label for="singles">Singles</label>
            </div>
            <div class="form-group">
                <input type ="radio" id="boosters" name="type" value="Boosters"><label for="boosters"> Boosters</label>
            </div>

            <div class="form-group">
                <input type ="radio" id="accessories" name="type" value="Accessories"><label for="accessories">Accessories</label>
            </div>
            <div class="form-group">
            <input type="submit" class="btn btn-block btn-primary" name="btn-create" value="Create Advert"/>
            </div>
        </div>
    </div>
    <!-- /.card -->

    <div class="card card-outline-secondary my-4">
        <div class="card-header">
            Your Details (this will be visible to other users so that they can contact you)
        </div>
        <div class="card-body">
            <p>Your details will be displayed here so others can contact you</p>
        </div>
    </div>
</form>
    <!-- /.card -->

</div>
<!-- /.col-lg-9 -->

</div>

</div>
<!-- /.container -->
<!-- Bootstrap core JavaScript -->
<script src="../vendor/jquery/jquery.min.js"></script>
<script src="../vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>

</html>

<?php require('views/footer.phtml') ?>




