<div class="container">

    <div class="row">

        <div class="col-lg-3">

            <h2 class="my-4">Your Account</h2>
            <div class="list-group">
                <a href="dashboard.php" class="list-group-item">Account Details</a>
                <a href="createadvert.php" class="list-group-item">Create Advert</a>
                <a href="youradverts.php" class="list-group-item">Your Adverts</a>
                <a href="savedadverts.php" class="list-group-item">Saved Adverts</a>
            </div>

        </div>