<?php require('views/navbar.phtml') ?>
<?php require_once ('models/connectdb.php');
require_once ('models/User.php');
$user = new User($connection);
if(!isset($_SESSION['username']))
    {
        $user->redirect('index.php');
    }
        $username = $_SESSION['username'];
        $sqlQuery = $connection->prepare("SELECT * FROM Users WHERE Username=:username");
        $sqlQuery->execute(array(":username"=>$username));
        $userRow=$sqlQuery->fetch(PDO::FETCH_ASSOC);
if(isset($_POST['logout']))
    {
        $user->logout();
        echo "logoutbeingcalled";
    }
?>
<div class="container">

    <div class="row">

        <div class="col-lg-3">

            <h1 class="my-4">Your Account</h1>
            <div class="list-group">
                <a href="#" class="list-group-item">Account Details</a>
                <a href="#" class="list-group-item">Your Adverts</a>
                <a href="#" class="list-group-item">Transactions</a>
                <a href="#" class="list-group-item">Saved Adverts</a>
            </div>

        </div>
    </div>

<form method="post">
    <button type="submit" id="logout" name="logout" class="btn btn-block btn-primary">
        <i class="glyphicon glyphicon-log-out"></i>&nbsp;Logout
    </button>
</form>

</div>
<div class="content">
    Welcome : <?php print($userRow['Username']); ?>
</div>
</body>
</html>
<?php require('views/footer.phtml') ?>
