
<?php require('views/navbar.phtml') ?>
    <!-- Page Content -->
    <div class="container">

      <div class="row">

        <div class="col-lg-3">
            <!--Displays session filter name-->
          <h1 class="my-4"><?php echo $_SESSION['filterName']?></h1>
            <form action="post" autocomplete="off">
                <div class="list-group">
                    <a href="?filter=1" class="list-group-item" name="filter1">Singles</a>
                    <a href="?filter=2" class="list-group-item" name="filter2">Booster Packs</a>
                    <a href="?filter=3" class="list-group-item" name="filter3">Accessories</a>
                    <a href="?filter=4" class="list-group-item" name="filter4">Name A-Z</a>
                    <input type="text" list="resultsSelectionBox" placeholder="Search by name" onkeyup="showHint(this.value)" id="search" class="list-group-item" name="query">
                    <p class="list-group-item">Suggested: <span id="txtHint"></span></p>
                    <select class="list-group-item" id="resultsSelectionBox" onchange="autoComplete()" autocomplete="off"></select>
                    <br>
                    <input type="submit" value="Search" class="btn btn-block btn-primary" name="search"/>

                </div>
            </form>
            <script>
                function showHint(str) {
                    if (str.length == 0) {
                        document.getElementById("txtHint").innerHTML = "";
                        return;
                    } else {
                        var xmlhttp = new XMLHttpRequest();
                        xmlhttp.onreadystatechange = function() {
                            if (this.readyState == 4 && this.status == 200) {
                                var uic = document.getElementById("txtHint");
                                uic.innerHTML = this.responseText;
                                uic = document.getElementById("resultsSelectionBox");
                                var names = this.responseText.split(',');
                                for (var i = 0; i<names.length; i++){
                                    var opt = document.createElement('option');
                                    opt.value = names[i];
                                    opt.innerHTML = names[i];
                                    if(!checkDuplicate(opt.value))
                                    {
                                        uic.appendChild(opt);
                                    }
                                }
                            }

                        };
                        xmlhttp.open("GET", "models/xmler.php?q=" + str, true);
                        xmlhttp.send();
                    }
                }
                function autoComplete()
                {
                    var autocomplete = document.getElementById('resultsSelectionBox').value;
                    document.getElementById('search').value = autocomplete;
                }
                function checkDuplicate(opt)
                {
                    for (i = 0; i < document.getElementById("resultsSelectionBox").length; ++i){
                        if (document.getElementById("resultsSelectionBox").options[i].value == opt){
                            return true;
                        }

                    }
                }
            </script>

        </div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9">

          <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
            <ol class="carousel-indicators">
              <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
              <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
              <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner" role="listbox">
              <div class="carousel-item active">
                <img class="d-block img-fluid" src="img/ixalanadvert.jpg" alt="First slide">
              </div>
              <div class="carousel-item">
                <img class="d-block img-fluid" src="img/mtgsinglesadvert.jpg" alt="Second slide">
              </div>
              <div class="carousel-item">
                <img class="d-block img-fluid" src="img/cardsleeveadvert.jpg" alt="Third slide">
              </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>

          <div class="row">
              <!--After fetching all adverts, loops through the object and returns advert details-->
              <?php

              foreach($view->adverts as $advert)
              {
                  echo "<div class=\"col-lg-4 col-md-6 mb-4\">
               <div class=\"card h-100\">
               <a href=\"advert.php?id=$advert->AdvertID\"><img class=\"card-img-top\" src=\"img/$advert->PhotoName\"  alt=\"\" name></a>
               <div class=\"card-body\">
               <h4 class=\"card-title\">
               
               <a href=\"advert.php?id=$advert->AdvertID\">$advert->AdvertName</a>
               </h4>
               <h5>£ $advert->AdvertPrice</h5>
               <p class=\"card-text\">$advert->AdvertDescription</p>
               </div>
               <div class=\"card-footer\">
               <small class=\"text-muted\">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
               </div>
               </div>
               </div>";
              }
              ?>

          </div>
          <!-- /.row -->

        </div>
        <!-- /.col-lg-9 -->

      </div>
      <!-- /.row -->

    </div>
    <!-- /.container -->



    <!-- Bootstrap core JavaScript -->
    <script src="../vendor/jquery/jquery.min.js"></script>
    <script src="../vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  </body>

</html>
    <?php require('Views/footer.phtml') ?>