<?php require('views/navbar.phtml');
require_once 'models/connectdb.php';
require_once ('models/User.php');
$user = new User($connection);
if($user->is_loggedin()!="")
{
$user->redirect('index.php');
}
if(isset($_POST['btn-login']))
{
$username = $_POST['username'];
$email = $_POST['username'];
$pass = $_POST['password'];
if($user->login($username,$email,$pass))
{
$user->redirect('index.php');
$_SESSION['username'] = $uname;
}
else
{
$error = "Wrong Details !";
}
}
?>

<div class="container">
    <div class="form-container">
        <form method="post">
            <h2>Sign in.</h2><hr />



            <div class="form-group">
                <input type="text" class="form-control" name="username" placeholder="Username or E mail ID" required />
            </div>
            <div class="form-group">
                <input type="password" class="form-control" name="password" placeholder="Your Password" required />
            </div>
            <div class="clearfix"></div><hr />
            <div class="form-group">
                <button type="submit" name="btn-login" class="btn btn-block btn-primary">
                    <i class="glyphicon glyphicon-log-in"></i>&nbsp;SIGN IN
                </button>
            </div>
            <br />
            <label>Don't have account yet ? <a href="register.php">Sign Up</a></label>
        </form>
    </div>
</div>
<?php require('Views/footer.phtml') ?>
