<?php require('views/navbar.phtml');?>


<div class="container">
    <div class="form-container">
        <form method="post">
            <h2>Sign in.</h2><hr />



            <div class="form-group">
                <input type="text" class="form-control" name="username" placeholder="Username"/>
            </div>
            <div class="form-group">
                <input type="text" class="form-control" name="email" placeholder="Email"/>
            </div>
            <div class="form-group">
                <input type="password" class="form-control" name="password" placeholder="Your Password"/>
            </div>
            <div class="form-group">
                <img src="models/captcha.php"/>
            </div>
            <div class="form-group">
                <input type="text" class ="form-control" name="code" placeholder="Enter Captcha code"/>
            </div>
            <div class="clearfix"></div><hr />
            <div class="form-group">
                <button type="submit" name="btn-login" class="btn btn-block btn-primary">
                    <i class="glyphicon glyphicon-log-in"></i>&nbsp;SIGN IN
                </button>
            </div>
            <br />
            <label>Don't have account yet ? <a href="register.php">Sign Up</a></label>
        </form>
    </div>
</div>
<?php require('Views/footer.phtml') ?>
