<?php require('views/navbar.phtml');?>

<div class="container">
    <div class="form-container">
        <form method="post">
            <h2>Sign up.</h2><hr />
            <?php
            if(isset($error)) {
                foreach($error as $error) {
                    ?>
                        <div class="alert alert-danger">
                            <i class="glyphicon glyphicon-warning-sign"></i> &nbsp; <?php echo $error; ?>
                        </div>
                    <?php
                }
            }
            else if(isset($_GET['registered']))
            {
                ?>
                    <div class="alert alert-info">
                        <i class="glyphicon glyphicon-log-in"></i> &nbsp; Successfully registered <a href='index.php'>Login</a> here
                    </div>
                    <?php
            }
            ?>

            <div class="form-group">
                <input type="text" class="form-control" name="username" placeholder="Enter Username" value="" />
            </div>
            <div class="form-group">
                <input type="text" class="form-control" name="email" placeholder="Enter E-Mail ID" value="" />
            </div>
            <div class="form-group">
                <input type="password" class="form-control" name="pass" placeholder="Enter Password" />
            </div>
            <div class="form-group">
                <input type="address" class="form-control" name="address" placeholder="Enter Postcode" />
            </div>
            <div class="form-group">
                <input type="phone" class="form-control" name="phone" placeholder="Enter Phone Number" />
            </div>
            <div class="clearfix"></div><hr />
            <div class="form-group">
                <button type="submit" class="btn btn-block btn-primary" name="btn-signup">
                    <i class="glyphicon glyphicon-open-file"></i>&nbsp;SIGN UP
                </button>
            </div>
            <br />
            <label>have an account ! <a href="login.php">Sign In</a></label>
        </form>
    </div>
</div>
<?php require('views/footer.phtml') ?>
