<?php require('views/navbar.phtml');?>
<div class="container">
    <div class="form-container">
        <form method="post">
            <h2>Sign up.</h2><hr />
            <div class="form-group">
                <input type="text" class="form-control" name="username" placeholder="Enter Username" value="" />
            </div>
            <div class="form-group">
                <input type="text" class="form-control" name="email" placeholder="Enter E-Mail ID" value="" />
            </div>
            <div class="form-group">
                <input type="password" class="form-control" name="pass" placeholder="Enter Password" />
            </div>
            <div class="form-group">
                <input type="text" class="form-control" name="address" placeholder="Enter Postcode" />
            </div>
            <div class="form-group">
                <input type="text" class="form-control" name="phone" placeholder="Enter Phone Number" />
            </div>
            <div class="form-group">
                <img src="models/captcha.php"/>
            </div>
            <div class="form-group">
                <input type="text" class ="form-control" name="code" placeholder="Enter Captcha code"/>
            </div>
            <div class="clearfix"></div>
            <div class="form-group">
                <button type="submit" class="btn btn-block btn-primary" name="btn-signup">Sign Up</button>
            </div>
            <br />
            <label>Have an account? <a href="login.php">Sign In</a></label>
        </form>
    </div>
</div>
<?php require('views/footer.phtml') ?>
