<?php require('views/navbar.phtml');?>
<?php require('views/dashnav.phtml');?>
    <div class="col-lg-9" id="nomargin">
        <h1>Your saved adverts are displayed here</h1>
        <div class="row">



    </div>
    <!-- /.row -->

    </div>
    <!-- /.container -->
    </div>
    </div>
    </body>
    </html>


    <!-- Bootstrap core JavaScript -->
    <script src="../vendor/jquery/jquery.min.js"></script>
    <script src="../vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<?php require('views/footer.phtml') ?>