<?php require('views/navbar.phtml');
require_once 'models/connectdb.php';
require_once('models/user.php');
//if user is logged in redirect them to index
if($user->is_loggedin()!="")
{
    $user->redirect('index.php');
}
//trimming the submitted data into post variables
if(isset($_POST['btn-signup']))
    {
        $username = trim($_POST['username']);
        $email = trim($_POST['email']);
        $pass = trim($_POST['pass']);
    }
//checking that the user has entered a value and/or a valid email address
if($username=="") {
    $error[] = "Please provide a username";
}
if($email =="") {
    $error[] = "Please provide an email";
}
if($pass=="") {
    $error[] = "Please provide a password";
}
else if(!filter_var($email, FILTER_VALIDATE_EMAIL)) {
    $error[] = "Please enter a valid email";
}
else if(strlen($pass) < 8) {
    $error[] = "Password must be at least 8 characters long";
}
//check if details entered have been taken by another user
else
    {
        try
        {
            //prepare statement to find matching username and emails
            $sqlQuery = $connection->prepare("SELECT Username, Email FROM Users WHERE Username=:username OR Email=:email");
            //execute statement and enter values into an array for easy access
            $sqlQuery->execute(array(':username'=>$username, ':email'=>$email));
            //fetches the associated rows
            $row=$sqlQuery->fetch(PDO::FETCH_ASSOC);
            //the checks
            if($row['username']==$username) {
                $error[] = "That username has already been taken";
            }
            else if($row['email']==$email) {
                $error[] = "Sorry that email has already been taken";
            }
            else
            {
                //call register function if it passes then redirect them to homepage
                if($user->register($username, $email, $pass))
                {
                    $user->redirect('index.php');
                }


            }
        }
        catch(PDOException $exception) {
            echo $exception->getMessage();
        }
    }
?>
<div class="container">
    <div class="form-container">
        <form method="post" action="<?php echo $_SERVER['PHP_SELF']; ?>">
            <h2>Sign up.</h2><hr />


            <div class="form-group">
                <input type="text" class="form-control" name="username" placeholder="Enter Username" value="" />
            </div>
            <div class="form-group">
                <input type="text" class="form-control" name="email" placeholder="Enter E-Mail ID" value="" />
            </div>
            <div class="form-group">
                <input type="password" class="form-control" name="pass" placeholder="Enter Password" />
            </div>
            <div class="clearfix"></div><hr />
            <div class="form-group">
                <button type="submit" class="btn btn-block btn-primary" name="btn-signup">
                    <i class="glyphicon glyphicon-open-file"></i>&nbsp;SIGN UP
                </button>
            </div>
            <br />
            <label>have an account ! <a href="index.php">Sign In</a></label>
        </form>
    </div>
</div>
<?php require('Views/footer.phtml') ?>
